# Generated by Django 4.1.1 on 2023-03-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="acc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.TextField()),
                ("title", models.TextField()),
                ("disc", models.TextField()),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="all",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.TextField()),
                ("title", models.TextField()),
                ("disc", models.TextField()),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="mobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.TextField()),
                ("title", models.TextField()),
                ("disc", models.TextField()),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="noacc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="noall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="nomob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no", models.IntegerField()),
            ],
        ),
    ]
